local colors = require("radium.colors")

return function(opts)
  local bg = opts.transparent and colors.none or colors.base

  return {
    ColorColumn = { bg = colors.line },
    Conceal = { fg = colors.text },
    CurSearch = { bg = colors.green, fg = colors.black },
    CursorLine = { bg = colors.line },
    Directory = { fg = colors.blue },
    DiffAdd = { fg = colors.green },
    DiffChange = { fg = colors.yellow },
    DiffDelete = { fg = colors.red },
    DiffText = { fg = colors.yellow },
    ErrorMsg = { fg = colors.red },
    WinSeparator = { fg = colors.border },
    Folded = { fg = colors.subtext },
    FoldColumn = { fg = colors.subtext },
    SignColumn = { bg = bg },
    IncSearch = { bg = colors.green, fg = colors.black },
    Substitute = { bg = colors.green, fg = colors.black },
    LineNr = { fg = colors.subtext },
    CursorLineNr = { fg = colors.text },
    CursorLineFold = { bg = bg },
    CursorLineSign = { bg = bg },
    MatchParen = { bg = colors.yellow, fg = colors.black },
    ModeMsg = { fg = colors.green },
    MsgArea = { fg = colors.text },
    NonText = { fg = colors.red },
    Normal = { bg = bg, fg = colors.text },
    NormalFloat = { bg = bg, fg = colors.text },
    FloatBorder = { bg = colors.border },
    FloatTitle = { fg = colors.text },
    NormalNC = { bg = bg, fg = colors.text },
    Pmenu = { bg = bg, fg = colors.text },
    PmenuSel = { bg = colors.line },
    PmenuSbar = { bg = colors.base },
    PmenuThumb = { bg = colors.base },
    Question = { fg = colors.subtext },
    QuickFixLine = { fg = colors.text },
    Search = { bg = colors.yellow, fg = colors.black },
    StatusLine = { bg = bg, fg = colors.text },
    StatusLineNC = { bg = bg, fg = colors.subtext },
    Visual = { bg = colors.selection },
    WarningMsg = { fg = colors.yellow },
  }
end
