local C = require("radium.colors")

return function(opts)
  return {
    Comment = { fg = C.subtext },
    SpecialComment = { fg = C.green },
    Constant = { fg = C.red },
    String = { fg = C.green },
    Character = { fg = C.green },
    Number = { fg = C.blue },
    Float = { fg = C.blue },
    Boolean = { fg = C.yellow },
    Identifier = { fg = C.text },
    Function = { fg = C.magenta },
    Statement = { fg = C.red },
    Conditional = { fg = C.red },
    Repeat = { fg = C.blue },
    Label = { fg = C.red },
    Operator = { fg = C.cyan },
    Keyword = { fg = C.red },
    Exception = { fg = C.blue },
    PreProc = { fg = C.red },
    Include = { fg = C.blue, style = { "bold" } },
    Define = { fg = C.blue },
    Macro = { fg = C.blue },
    PreCondit = { fg = C.red },
    StorageClass = { fg = C.yellow },
    Structure = { fg = C.blue },
    Special = { fg = C.green },
    Type = { fg = C.text },
    Typedef = { fg = C.blue },
    SpecialChar = { fg = C.blue },
    Tag = { fg = C.blue },
    Delimiter = { fg = C.text },
    Debug = { fg = C.red },
    Underlined = { style = { "underline" } },
    Bold = { style = { "bold" } },
    Italic = { style = { "italic" } },
    Error = { fg = C.red },
    Todo = { fg = C.yellow, style = { "bold" } },
  }
end
