local colors = require("radium.colors")

return {
  Comment = { fg = colors.subtext },
  SpecialComment = { fg = colors.green },
  Constant = { fg = colors.red },
  String = { fg = colors.green },
  Character = { fg = colors.green },
  Number = { fg = colors.blue },
  Float = { fg = colors.blue },
  Boolean = { fg = colors.yellow },
  Identifier = { fg = colors.text },
  Function = { fg = colors.magenta },
  Statement = { fg = colors.red },
  Conditional = { fg = colors.red },
  Repeat = { fg = colors.blue },
  Label = { fg = colors.red },
  Operator = { fg = colors.cyan },
  Keyword = { fg = colors.red },
  Exception = { fg = colors.blue },
  PreProc = { fg = colors.red },
  Include = { fg = colors.blue },
  Define = { fg = colors.blue },
  Macro = { fg = colors.blue },
  PreCondit = { fg = colors.red },
  StorageClass = { fg = colors.yellow },
  Structure = { fg = colors.blue },
  Special = { fg = colors.magenta },
  Type = { fg = colors.text },
  Typedef = { fg = colors.blue },
  SpecialChar = { fg = colors.blue },
  Tag = { fg = colors.blue },
  Delimiter = { fg = colors.text },
  Debug = { fg = colors.red },
  Underlined = { style = { "underline" } },
  Bold = { style = { "bold" } },
  Italic = { style = { "italic" } },
  Error = { fg = colors.red },
  Todo = { fg = colors.yellow },
}
